=== MGDevelopment/site-jrun/site/setup/server.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp2 (http://www.altova.com) by Miguel (Miguel) -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Sistemas (ILHSA) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="ModoType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="debug"/>
			<xs:enumeration value="backup"/>
			<xs:enumeration value="mantenimiento"/>
			<xs:enumeration value="reset"/>
			<xs:enumeration value="release"/>
			<xs:enumeration value="inicializacion"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LogType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="alto"/>
			<xs:enumeration value="medio"/>
			<xs:enumeration value="bajo"/>
			<xs:enumeration value="ninguno"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DiaType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="lunes"/>
			<xs:enumeration value="martes"/>
			<xs:enumeration value="miercoles"/>
			<xs:enumeration value="jueves"/>
			<xs:enumeration value="viernes"/>
			<xs:enumeration value="sabado"/>
			<xs:enumeration value="domingo"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Server">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Aplicacion" type="AplicacionType"/>
				<xs:element name="Log" type="LogType"/>
				<xs:element name="Modo" type="ModoType"/>
				<xs:element name="Mailing">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="mailer" type="xs:string" use="required"/>
						<xs:attribute name="smtpHost" type="xs:string" use="required"/>
						<xs:attribute name="webmasterMail" type="xs:string" use="required"/>
						<xs:attribute name="serverMail" type="xs:string" use="required"/>
						<xs:attribute name="mailLargos" type="xs:boolean" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Control">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="iteraciones" type="xs:int" use="required"/>
						<xs:attribute name="memoriaAlerta" type="xs:int" use="required"/>
						<xs:attribute name="memoriaMaxima" type="xs:int" use="required"/>
						<xs:attribute name="consola" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ProgramaExtra">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="GPay">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Errores">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Error" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="mensajePorDefecto" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="host" type="xs:string" use="required"/>
						<xs:attribute name="port" type="xs:int" use="required"/>
						<xs:attribute name="comercio" type="xs:string" use="required"/>
						<xs:attribute name="mensaje" type="xs:string" use="required"/>
						<xs:attribute name="baseTerminal" type="xs:string" use="required"/>
						<xs:attribute name="tiempoEsperaMaxima" type="xs:int" use="required"/>
						<xs:attribute name="cantidadDeTerminales" type="xs:int" use="required"/>
						<xs:attribute name="habilitaCuotas" type="xs:boolean" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Inactividad">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Cronograma">
								<xs:complexType>
									<xs:attribute name="modo" type="ModoType" use="required"/>
									<xs:attribute name="dia" type="DiaType" use="required"/>
									<xs:attribute name="comienzo" type="xs:time" use="required"/>
									<xs:attribute name="fin" type="xs:time" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="mensajeMantenimiento" type="xs:string" use="required"/>
						<xs:attribute name="mensajePrevio" type="xs:string" use="required"/>
						<xs:attribute name="minutosDeAnticipacion" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ProgramaReferido">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="vigenciaReferente" type="xs:int" use="required"/>
						<xs:attribute name="vigenciaReferido" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="PromoChequeObsequio">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="codigoChequeObsequio" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="PromoDiaDeLaMadre">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="pesosPorCupon" type="xs:double" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="BloqueoIP">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="hits" type="xs:int" use="required"/>
						<xs:attribute name="tiempoEntreHits" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Dominios">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Principal" type="xs:string"/>
							<xs:element name="Secundario" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MusicaOnLine">
					<xs:complexType>
						<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
						<xs:attribute name="seccion" type="xs:int" use="required"/>
						<xs:attribute name="grupo" type="xs:int" use="required"/>
						<xs:attribute name="familia" type="xs:int" use="required"/>
						<xs:attribute name="subfamilia" type="xs:int" use="required"/>
						<xs:attribute name="disponibilidad" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ProcesosBackground">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Proceso" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" use="required"/>
									<xs:attribute name="nombre" type="xs:string" use="required"/>
									<xs:attribute name="habilitado" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Generacion">
					<xs:complexType>
						<xs:attribute name="sentenciaDeMapeo" type="xs:string" use="required"/>
						<xs:attribute name="directorioDeGeneracion" type="xs:string" use="required"/>
						<xs:attribute name="directorioRaiz" type="xs:string" use="required"/>
						<xs:attribute name="sentenciaDeDesMapeo" type="xs:string" use="required"/>
						<xs:attribute name="url" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Procesos" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="0">
							<xs:element name="RunPro" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0">
										<xs:element name="DiaSemana" minOccurs="0" maxOccurs="7">
											<xs:simpleType>
												<xs:restriction base="xs:int">
													<xs:enumeration value="1"/>
													<xs:enumeration value="2"/>
													<xs:enumeration value="3"/>
													<xs:enumeration value="4"/>
													<xs:enumeration value="5"/>
													<xs:enumeration value="6"/>
													<xs:enumeration value="7"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="Email" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="nombre" type="xs:string" use="required"/>
									<xs:attribute name="clase" type="xs:string" use="required"/>
									<xs:attribute name="metodo" type="xs:string" use="required"/>
									<xs:attribute name="comienzo" type="xs:string" use="required"/>
									<xs:attribute name="espera" type="xs:string" use="required"/>
									<xs:attribute name="dia" type="xs:string" use="optional"/>
									<xs:attribute name="hora" type="xs:string" use="optional"/>
									<xs:attribute name="minuto" type="xs:string" use="optional"/>
									<xs:attribute name="rangoRepMen" type="xs:string" use="optional"/>
									<xs:attribute name="rangoRepMay" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="UbicacionDeRed" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="0">
							<xs:element name="Ubicacion" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" use="required"/>
									<xs:attribute name="user" type="xs:string" use="required"/>
									<xs:attribute name="password" type="xs:string" use="required"/>
									<xs:attribute name="host" type="xs:string" use="required"/>
									<xs:attribute name="ip" type="xs:string" use="required"/>
									<xs:attribute name="defaultDir" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="url" type="xs:string" use="required"/>
			<xs:attribute name="modoAplicacionHabilitado" type="xs:boolean" use="required"/>
			<xs:attribute name="dominioSitio" type="xs:string" use="required"/>
			<xs:attribute name="dominioIntranet" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Error">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Email" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:int" use="required"/>
			<xs:attribute name="mensajeAMostrar" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="AplicacionType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="intranet"/>
			<xs:enumeration value="sitio"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Email" type="xs:string"/>
</xs:schema>

=== MGDevelopment/site-jrun/site/setup/server_prod.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Server xsi:noNamespaceSchemaLocation="server.xsd"
    url="http://www.tematika.com" modoAplicacionHabilitado="false"
    dominioSitio="www.tematika.com" dominioIntranet="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Aplicacion>sitio</Aplicacion>
    <Log>alto</Log>
    <Modo>release</Modo>
    <Mailing habilitado="true" mailer="server@tematika.com"
        smtpHost="172.29.0.20"
        webmasterMail="clopez@ilhsa.com"
        serverMail="http://172.29.0.20" mailLargos="true"/>
    <Control habilitado="true" iteraciones="2" memoriaAlerta="45000"
        memoriaMaxima="1040000" consola="taskkill /F /IM jrun.exe"/>
    <ProgramaExtra habilitado="true"/>
    <GPay host="172.29.0.10" port="20001" comercio="tematikasite"
        mensaje="COMPRA EN TEMATIKA" baseTerminal="tematika-"
        tiempoEsperaMaxima="60" cantidadDeTerminales="7" habilitaCuotas="true">
        <Errores mensajePorDefecto="Su operación ha fallado por un problema de comunicación. Por favor, intente nuevamente más tarde y disculpe las molestias ocasionadas.">
            <Error codigo="0" mensajeAMostrar="Su operación ha fallado por un problema de comunicación. Por favor, intente nuevamente más tarde y disculpe las molestias ocasionadas."/>
            <Error codigo="1" mensajeAMostrar="La operación no ha sido aprobada ya que ha ingresado algún dato de su tarjeta en forma errónea. Por favor, verifique la fecha de vencimiento y el código de seguridad y vuelva a intentar el pago."/>
            <Error codigo="2" mensajeAMostrar="La operación no ha sido aprobada ya que ha ingresado algún dato de su tarjeta en forma errónea. Por favor, verifique la fecha de vencimiento y el código de seguridad y vuelva a intentar el pago."/>
            <Error codigo="4" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras. Le pedimos por favor se contacte con el Banco o Entidad emisora de la misma para regularizar la situación."/>
            <Error codigo="5" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras. Le pedimos por favor se contacte con el Banco o Entidad emisora de la misma para regularizar la situación."/>
            <Error codigo="7" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras. Le pedimos por favor se contacte con el Banco o Entidad emisora de la misma para regularizar la situación."/>
            <Error codigo="12" mensajeAMostrar="Por favor, verifique que todos los datos ingresados sean correctos e intente nuevamente la operación. Tenga en cuenta que las tarjetas de débito no se encuentran habilitadas en nuestro sistema para realizar compras y que solamente podrá operar en cuotas en caso de utilizar una tarjeta de procedencia Argentina."/>
            <Error codigo="14" mensajeAMostrar="Por favor, verifique que todos los datos ingresados sean correctos e intente nuevamente la operación. Tenga en cuenta que las tarjetas de débito no se encuentran habilitadas en nuestro sistema para realizar compras."/>
            <Error codigo="25" mensajeAMostrar="La operación no ha sido aprobada ya que ha ingresado algún dato de su tarjeta en forma errónea. Por favor, verifique la fecha de vencimiento y el código de seguridad y vuelva a intentar el pago."/>
            <Error codigo="30" mensajeAMostrar="Por favor, verifique que todos los datos ingresados sean correctos e intente nuevamente la operación. Tenga en cuenta que las tarjetas de débito no se encuentran habilitadas en nuestro sistema para realizar compras."/>
            <Error codigo="43" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras. Le pedimos por favor se contacte con el Banco o Entidad emisora de la misma para regularizar la situación."/>
            <Error codigo="45" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras en cuotas en nuestro site. Le pedimos por favor realice el pedido a través del pago en una única cuota. Muchas gracias."/>
            <Error codigo="48" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras en cuotas en nuestro site. Le pedimos por favor realice el pedido a través del pago en una única cuota. Muchas gracias."/>
            <Error codigo="50" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras ya que no posee los fondos suficientes para realizar esta operación."/>
            <Error codigo="51" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras ya que no posee los fondos suficientes para realizar esta operación."/>
            <Error codigo="53" mensajeAMostrar="La operación no ha sido aprobada ya que ha ingresado algún dato de su tarjeta en forma errónea. Por favor, verifique los datos ingresados y vuelva a intentar el pago."/>
            <Error codigo="54" mensajeAMostrar="Su tarjeta se encuentra inhabilitada para generar compras ya que la misma se encuentra vencida. Verifique los datos ingresados y en caso de ser correctos comuníquese con el Banco o Entidad emisora de la misma para regularizar la situación."/>
            <Error codigo="57" mensajeAMostrar="Por favor, verifique que todos los datos ingresados sean correctos e intente nuevamente la operación. Tenga en cuenta que las tarjetas de débito no se encuentran habilitadas en nuestro sistema para realizar compras."/>
            <Error codigo="77" mensajeAMostrar="Por favor, verifique que todos los datos ingresados sean correctos e intente  nuevamente la operación. Tenga en cuenta que las tarjetas de débito no se encuentran habilitadas en nuestro sistema para realizar compras y que solamente podrá operar en cuotas en caso de utilizar una tarjeta de procedencia Argentina."/>
            <Error codigo="94" mensajeAMostrar="Su compra se encuentra en proceso de aprobación y será contactado por nuestro personal de Atención al Cliente para verificar sus datos. El contacto se realizará a la mayor brevedad posible vía mail o telefónicamente al número ingresado en el pedido. Le recordamos que nuestro horario de atención es de Lunes a Viernes de 9 a 20hs. Muchas Gracias.">
                <Email>rmiranda@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
            </Error>
            <Error codigo="96" mensajeAMostrar="Su operación ha fallado por un problema de comunicación. Por favor, intente nuevamente más tarde y disculpe las molestias ocasionadas."/>
            <Error codigo="110">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>                
            </Error>
            <Error codigo="111">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>        
            </Error>
            <Error codigo="120">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>        
            </Error>
            <Error codigo="121">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>        
            </Error>
            <Error codigo="130">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>        
            </Error>
            <Error codigo="131">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>        
            </Error>
            <Error codigo="141">
                <Email>apaz@ilhsa.com</Email>
                <Email>clopez@ilhsa.com</Email>
                <Email>sistemassoporte@ilhsa.com</Email>
                <Email>ffulleringer@ilhsa.com</Email>
                <Email>cdiaz@ilhsa.com</Email>
                <Email>slaguna@ilhsa.com</Email>
                <Email>jpiermattei@ilhsa.com</Email>
                <Email>aandreoli@ilhsa.com</Email>        
            </Error>
